### ISSUE TITLE
コメントに入っているhato-botに依存したミーム成分をなくす

### ISSUE THREAD

**Issue by fono09** [dev-hato/sudden-death#9]
流石に他所にPR出すときにこれは無理。

**Comment by Goryudyuma** [comment]
他所にPR出すの？

**Comment by massongit** [comment]
個人的にはそういう方向でも動けるようにしたいなとは思う (OSSへの貢献的な意味で)

**Comment by Goryudyuma** [comment]
んー、pipenv入れたりclipboardを消そうと考えたりしてる時点で、ちょっと難しいんじゃないかなーと。

**Comment by massongit** [comment]
細かく出して、反映してもらえるとこだけ反映してもらえばいいのかなって

**Comment by Goryudyuma** [comment]
だとしたら、PRとして出す部分を選定して、削って出すってことでしょ？じゃあそのときに削ればいいんじゃないかな、と思った
このリポジトリの使いみちはhato-botのみなので、コメントはこのままでもいいと思う

**Comment by fono09** [comment]
特に意識しなくても良さそうなので一旦閉じまーす
